name: release

on:
  push:
    branches:
    - main
  
jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - name: Manual Build
        run: python setup.py sdist bdist_wheel
      - name: Check build folder
        run: ls ./dist/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
